// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package json

// Valid reports whether data is a valid JSON encoding.
Valid!: _ @stdlib(validator(bytes|string))

// Compact generates the JSON-encoded src with insignificant space characters
// elided.
Compact!: _ @stdlib(func(_~src: bytes|string) -> string)

// Indent creates an indented form of the JSON-encoded src.
// Each element in a JSON object or array begins on a new,
// indented line beginning with prefix followed by one or more
// copies of indent according to the indentation nesting.
// The data appended to dst does not begin with the prefix nor
// any indentation, to make it easier to embed inside other formatted JSON data.
// Although leading space characters (space, tab, carriage return, newline)
// at the beginning of src are dropped, trailing space characters
// at the end of src are preserved and copied to dst.
// For example, if src has no trailing spaces, neither will dst;
// if src ends in a trailing newline, so will dst.
Indent!: _ @stdlib(func(_~src: bytes|string, _~prefix: string, _~indent: string) -> string)

// HTMLEscape returns the JSON-encoded src with <, >, &, U+2028 and
// U+2029 characters inside string literals changed to \u003c, \u003e, \u0026,
// \u2028, \u2029 so that the JSON will be safe to embed inside HTML <script>
// tags. For historical reasons, web browsers don't honor standard HTML escaping
// within <script> tags, so an alternative JSON encoding must be used.
HTMLEscape!: _ @stdlib(func(_~src: bytes|string) -> string)

// Marshal returns the JSON encoding of v.
Marshal!: _ @stdlib(func(_~v: _) -> string)

// MarshalStream turns a list into a stream of JSON objects.
MarshalStream!: _ @stdlib(func(_~v: _) -> string)

// UnmarshalStream parses the JSON to a CUE instance.
UnmarshalStream!: _ @stdlib(func(_~data: bytes|string) -> _)

// Unmarshal parses the JSON-encoded data.
Unmarshal!: _ @stdlib(func(_~b: bytes|string) -> _)

// Validate validates JSON and confirms it matches the constraints
// specified by v.
Validate!: _ @stdlib(func(_~v: _) -> validator(bytes|string))
