// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package yaml

// Marshal returns the YAML encoding of v.
Marshal!: _ @stdlib(func(_~v: _) -> string)

// MarshalStream returns the YAML encoding of v.
MarshalStream!: _ @stdlib(func(_~v: _) -> string)

// Unmarshal parses the YAML to a CUE expression.
Unmarshal!: _ @stdlib(func(_~data: bytes|string) -> _)

// UnmarshalStream parses the YAML to a CUE list expression on success.
UnmarshalStream!: _ @stdlib(func(_~data: bytes|string) -> _)

// Validate validates YAML and confirms it is an instance of schema.
// If the YAML source is a stream, every object must match v.
Validate!: _ @stdlib(func(_~v: _) -> validator(bytes|string))

// ValidatePartial validates YAML and confirms it matches the constraints
// specified by v using unification. This means that b must be consistent with,
// but does not have to be an instance of v. If the YAML source is a stream,
// every object must match v.
ValidatePartial!: _ @stdlib(func(_~v: _) -> validator(bytes|string))
