// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package sha512

// Size is the size, in bytes, of a SHA-512 checksum.
Size: 64

// Size224 is the size, in bytes, of a SHA-512/224 checksum.
Size224: 28

// Size256 is the size, in bytes, of a SHA-512/256 checksum.
Size256: 32

// Size384 is the size, in bytes, of a SHA-384 checksum.
Size384: 48

// BlockSize is the block size, in bytes, of the SHA-512/224,
// SHA-512/256, SHA-384 and SHA-512 hash functions.
BlockSize: 128

// Sum512 returns the SHA512 checksum of the data.
Sum512!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)

// Sum384 returns the SHA384 checksum of the data.
Sum384!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)

// Sum512_224 returns the Sum512/224 checksum of the data.
Sum512_224!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)

// Sum512_256 returns the Sum512/256 checksum of the data.
Sum512_256!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)
