// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

// Package hmac implements the Keyed-Hash Message Authentication Code (HMAC) as
// defined in U.S. Federal Information Processing Standards Publication 198.
//
// An HMAC is a cryptographic hash that uses a key to sign a message.
// The receiver verifies the hash by recomputing it using the same key.
package hmac

MD5: "MD5"

SHA1: "SHA1"

SHA224: "SHA224"

SHA256: "SHA256"

SHA384: "SHA384"

SHA512: "SHA512"

SHA512_224: "SHA512_224"

SHA512_256: "SHA512_256"

// Sign returns the HMAC signature of the data, using the provided key and hash function.
//
// Supported hash functions: "MD5", "SHA1", "SHA224", "SHA256", "SHA384", "SHA512", "SHA512_224",
// and "SHA512_256".
Sign!: _ @stdlib(func(_~hashName: string, _~key: bytes|string, _~data: bytes|string) -> bytes|string)
