// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package ed25519

// PublicKeySize is the size of a public key in bytes.
PublicKeySize: 32

// Valid verifies the provided signature of the message using the public key.
// An error is returned if and only if an invalid public key is provided.
Valid!: _ @stdlib(func(_~message: bytes|string, _~signature: bytes|string) -> validator(bytes|string))
