// Code generated by gocode.Generate; DO NOT EDIT.

package pkg1

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/encoding/gocode/gocodec"
	_ "cuelang.org/go/pkg"
)

var cuegenvalMyStruct = cuegenMake("MyStruct", &MyStruct{})

// Validate validates x.
func (x *MyStruct) Validate() error {
	return cuegenCodec.Validate(cuegenvalMyStruct, x)
}

// Complete completes x.
func (x *MyStruct) Complete() error {
	return cuegenCodec.Complete(cuegenvalMyStruct, x)
}

var cuegenvalOtherStruct = cuegenMake("OtherStruct", &OtherStruct{})

// Validate validates x.
func (x *OtherStruct) Validate() error {
	return cuegenCodec.Validate(cuegenvalOtherStruct, x)
}

var cuegenvalString = cuegenMake("String", nil)

// ValidateCUE validates x.
func (x String) ValidateCUE() error {
	return cuegenCodec.Validate(cuegenvalString, x)
}

var cuegenvalSpecialString = cuegenMake("SpecialString", nil)

// ValidateSpecialString validates x.
func ValidateSpecialString(x string) error {
	return cuegenCodec.Validate(cuegenvalSpecialString, x)
}

var cuegenvalPtr = cuegenMake("Ptr", Ptr(nil))

// ValidatePtr validates x.
func ValidatePtr(x Ptr) error {
	return cuegenCodec.Validate(cuegenvalPtr, x)
}

var cuegenCodec, cuegenInstance_, cuegenValue = func() (*gocodec.Codec, *cue.Instance, cue.Value) {
	var r *cue.Runtime
	r = &cue.Runtime{}
	instances, err := r.Unmarshal(cuegenInstanceData)
	if err != nil {
		panic(err)
	}
	if len(instances) != 1 {
		panic("expected encoding of exactly one instance")
	}
	return gocodec.New(r, nil), instances[0], instances[0].Value()
}()

// Deprecated: cue.Instance is deprecated. Use cuegenValue instead.
var cuegenInstance = cuegenInstance_

// cuegenMake is called in the init phase to initialize CUE values for
// validation functions.
func cuegenMake(name string, x interface{}) cue.Value {
	f, err := cuegenValue.FieldByName(name, true)
	if err != nil {
		panic(fmt.Errorf("could not find type %q in instance", name))
	}
	v := f.Value
	if x != nil {
		w, err := cuegenCodec.ExtractType(x)
		if err != nil {
			panic(err)
		}
		v = v.Unify(w)
	}
	return v
}

// Data size: 607 bytes.
var cuegenInstanceData = []byte("\x01\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xff\x94\x92Oo\xdbF\x10\xc5w)\x15(\an\x81~\x80\x02\xd3=\x89\x85KJ\x02\xda\x03a6\xfe\x13'\xf0\xc1\x96\x10;A\x90 \x87\x159\xa2\x16\xa6v\x19q\xe9Xp\xec$\x8e\xe3\x8fm\x06\xa4$[9\xe4`\x9e\x1e\x86\x9cy?\u03bc\u07eao\x0ew\xaa[\u01ab\u03cc\xfd\xf7\xa9\xc5\xf9\x86\u0485\x95:\xa6\xa7\xd2\u02ba\xcc[\xbc\xfd\xc2\x18\xcb\x1d\xc6\xdbCi'|\x83\xf1_\x9e\xa9\x8c\n^\xdd0\xc6\xfe\xac\xbe:\x9c\xff\xfe\xf6]\\\x92?V\u0672\xf3\x86\xf1\ua6b1N\xf5\xa5\xc5\xf9\xaf\x0f\xf5k\xc6\x1d\xde>\x92S\xaa\a\xb5\x9b\"0\xc6\xeeZ'\xd5-s8\xe7A\\R&u\xea\x9bY\x1a\xa4& \x1d\x9bD\xe9Z\xc7&\xa1\xc0Ra\x13ie\x90\x9f\xa6\xbd\xed\xb3.\xe7\xfc\x8fZ\x06+t?.\x89\xdf9or\x19\x9f\u0294\xb0~\t\xa0\xa6\xb9\x99Y\xec\x80+\x1ea\xd0\x17\xe0\x8a\xc2\u0394N\x8bZN\xa5\x9d\b\xf0\x00\x0e\xe7\xc7vV\xc66\xc4\vpwB\u012d\xa8\xd7\x05w7D\x8c\xaeD,\xad\xc0\x8f\xf8\xb7HL*\xc0\x1d<\tq`'4[\xf4\x80{\x10b\x8d\xd5\xf7\x0f\x1a\xaaC\x82K\xdcNMg36\xd3<#K\xd1\xdeRx\xb0\u05b82[\x02\xf9{F[\xa9t\xb1\xa3\xe7\x1d\xf1Zx\xe0\x0e\xc3\xc5\u0721\x8aO\xeb\xa9p\xdc|\x1a\xe2\xf2\xf9+\x12b\xa5\x1b\xc33\x99\xa9DZ\x8a^-\xc5\xde\xcb}\x0f\x8es\x8a\x95\xccV\xcd\u0455(\x16\x15\xb1\xc0\xb4\xf3\x9c\xa2\x05\x85\a\a\xa963:\x99\xa8\xa2\xb1\x89\xae\xc4\xd8\x18\x01\x83\xa9\xb2\xf7\xbe\x88J\u06d5lf\xfc\xe3\x01\x04\x01\x1e\x19\xbd\x7f\xae\n\xabt\x8a\x1fT\x96\xe1\x88\xd0L\x95\xb5\x94\xa0,\xb0\xfewBU\xa06H\xefKu&3\xd2\x16\x9f\x1b\xac\x11|Xk\x0f\xf1bw\xb5\x9a\xcbu\v\xd5\xf0a\xa9\xe9\xbc^6%X\ua30a\x02\xe9<\xcfT\xacl6G\xd2r\x94Q\xe2\xc3\u0618\xb0f\x85\xa1\x9d\x85\xb8\x13b}q\xff\xb0\u032c\xca3\x1a\x8c;\xbd\xae\a\x8c9\x9b\x8f\t\xd12\xa2\xfd\x1f#*\xd7\x02\u06bf\x0f\xe8C\xda`\x15\x8e\xe6\xec2\u012d^\xb7\v\xee\xe8'\xf7\x97\xa3Xxp\t\x8b\u04c7\xf8\xff\xbf\xc0\xd8\xf7\x01\x00\x93\xa4O\xea\xe3\x03\x00\x00")
