// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package hex

// EncodedLen returns the length of an encoding of n source bytes.
// Specifically, it returns n * 2.
EncodedLen!: _ @stdlib(func(_~n: int) -> int)

// DecodedLen returns the length of a decoding of x source bytes.
// Specifically, it returns x / 2.
DecodedLen!: _ @stdlib(func(_~x: int) -> int)

// Decode returns the bytes represented by the hexadecimal string s.
//
// Decode expects that s contains only hexadecimal
// characters and that s has even length.
// If the input is malformed, Decode returns
// the bytes decoded before the error.
Decode!: _ @stdlib(func(_~s: string) -> bytes|string)

// Dump returns a string that contains a hex dump of the given data. The format
// of the hex dump matches the output of `hexdump -C` on the command line.
Dump!: _ @stdlib(func(_~data: bytes|string) -> string)

// Encode returns the hexadecimal encoding of src.
Encode!: _ @stdlib(func(_~src: bytes|string) -> string)
