// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package html

// Escape escapes special characters like "<" to become "&lt;". It
// escapes only five such characters: <, >, &, ' and ".
// Unescape(Escape(s)) == s always holds, but the converse isn't
// always true.
Escape!: _ @stdlib(func(_~s: string) -> string)

// Unescape unescapes entities like "&lt;" to become "<". It unescapes a
// larger range of entities than Escape escapes. For example, "&aacute;"
// unescapes to "á", as does "&#225;" and "&#xE1;".
// Unescape(Escape(s)) == s always holds, but the converse isn't
// always true.
Unescape!: _ @stdlib(func(_~s: string) -> string)
