// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

// Package struct defines utilities for struct types.
package struct

// MinFields validates the minimum number of fields that are part of a struct.
// It can only be used as a validator, for instance `MinFields(3)`.
//
// Only fields that are part of the data model count. This excludes hidden
// fields, optional fields, and definitions.
MinFields!: _ @stdlib(func(_~n: int) -> validator({...}))

// MaxFields validates the maximum number of fields that are part of a struct.
// It can only be used as a validator, for instance `MaxFields(3)`.
//
// Only fields that are part of the data model count. This excludes hidden
// fields, optional fields, and definitions.
MaxFields!: _ @stdlib(func(_~n: int) -> validator({...}))
