// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

// Package net provides net-related type definitions.
//
// The IP-related definitions can be represented as either a string or a list of
// byte values. To allow one format over an other these types can be further
// constraint using string or [...]. For instance,
//
// 	// multicast defines a multicast IP address in string form.
// 	multicast: net.MulticastIP & string
//
// 	// unicast defines a global unicast IP address in list form.
// 	unicast: net.GlobalUnicastIP & [...]
package net

// SplitHostPort splits a network address of the form "host:port",
// "host%zone:port", "[host]:port" or "[host%zone]:port" into host or host%zone
// and port.
//
// A literal IPv6 address in hostport must be enclosed in square brackets, as in
// "[::1]:80", "[::1%lo0]:80".
SplitHostPort!: _ @stdlib(func(_~s: string) -> [...string])

// JoinHostPort combines host and port into a network address of the
// form "host:port". If host contains a colon, as found in literal
// IPv6 addresses, then JoinHostPort returns "[host]:port".
//
// See func Dial for a description of the host and port parameters.
JoinHostPort!: _ @stdlib(func(_~host: _, _~port: _) -> string)

// FQDN reports whether is a valid fully qualified domain name.
//
// FQDN allows only ASCII characters as prescribed by RFC 1034 (A-Z, a-z, 0-9
// and the hyphen).
FQDN!: _ @stdlib(validator(string))

IPv4len: 4

IPv6len: 16

// ParseIP parses s as an IP address, returning the result.
// The string s can be in dotted decimal ("192.0.2.1")
// or IPv6 ("2001:db8::68") form.
// If s is not a valid textual representation of an IP address,
// ParseIP returns an error.
ParseIP!: _ @stdlib(func(_~s: string) -> [...])

// IPv4 reports whether ip is a valid IPv4 address.
//
// The address may be a string or list of bytes.
IPv4!: _ @stdlib(validator(_))

// IPv6 reports whether ip is a valid IPv6 address.
//
// The address may be a string or list of bytes.
IPv6!: _ @stdlib(validator(_))

// IP reports whether ip is a valid IPv4 or IPv6 address.
//
// The address may be a string or list of bytes.
IP!: _ @stdlib(validator(_))

// IPCIDR reports whether ip is a valid IPv4 or IPv6 address with CIDR subnet notation.
//
// The address may be a string or list of bytes.
IPCIDR!: _ @stdlib(validator(_))

// LoopbackIP reports whether ip is a loopback address.
LoopbackIP!: _ @stdlib(validator(_))

// MulticastIP reports whether ip is a multicast address.
MulticastIP!: _ @stdlib(validator(_))

// InterfaceLocalMulticastIP reports whether ip is an interface-local multicast
// address.
InterfaceLocalMulticastIP!: _ @stdlib(validator(_))

// LinkLocalMulticastIP reports whether ip is a link-local multicast address.
LinkLocalMulticastIP!: _ @stdlib(validator(_))

// LinkLocalUnicastIP reports whether ip is a link-local unicast address.
LinkLocalUnicastIP!: _ @stdlib(validator(_))

// GlobalUnicastIP reports whether ip is a global unicast address.
//
// The identification of global unicast addresses uses address type
// identification as defined in RFC 1122, RFC 4632 and RFC 4291 with the
// exception of IPv4 directed broadcast addresses. It returns true even if ip is
// in IPv4 private address space or local IPv6 unicast address space.
GlobalUnicastIP!: _ @stdlib(validator(_))

// UnspecifiedIP reports whether ip is an unspecified address, either the IPv4
// address "0.0.0.0" or the IPv6 address "::".
UnspecifiedIP!: _ @stdlib(validator(_))

// ToIP4 converts a given IP address, which may be a string or a list, to its
// 4-byte representation.
ToIP4!: _ @stdlib(func(_~ip: _) -> [...])

// ToIP16 converts a given IP address, which may be a string or a list, to its
// 16-byte representation.
ToIP16!: _ @stdlib(func(_~ip: _) -> [...])

// IPString returns the string form of the IP address ip. It returns one of 4 forms:
//
// - "<nil>", if ip has length 0
// - dotted decimal ("192.0.2.1"), if ip is an IPv4 or IP4-mapped IPv6 address
// - IPv6 ("2001:db8::1"), if ip is a valid IPv6 address
// - the hexadecimal form of ip, without punctuation, if no other cases apply
IPString!: _ @stdlib(func(_~ip: _) -> string)

// AddIP adds a numerical offset to a given IP address.
// The address can be provided as a string, byte array, or CIDR subnet notation.
// It returns the resulting IP address or CIDR subnet notation as a string.
AddIP!: _ @stdlib(func(_~ip: _, _~offset: int) -> string)

// AddIPCIDR adds a numerical offset to a given CIDR subnet
// string, returning a CIDR string.
AddIPCIDR!: _ @stdlib(func(_~ip: _, _~offset: int) -> string)

// ParseCIDR parses a CIDR notation string and returns its components:
// prefix_mask (e.g. "255.255.255.0"), prefix_len (e.g. 24),
// prefix_addr (e.g. "10.20.30.0"), and broadcast_addr (e.g. "10.20.30.255").
// broadcast_addr is only set for IPv4 CIDRs.
ParseCIDR!: _ @stdlib(func(_~s: string) -> {...})

// InCIDR reports whether an IP address is contained a CIDR subnet string.
InCIDR!: _ @stdlib(func(_~cidr: _) -> validator(_))

// CompareIP compares two IP addresses and returns an integer:
// -1 if ip1 sorts before ip2, 0 if they are equal, and +1 if ip1 sorts after ip2.
// IPv4 addresses sort before IPv6 addresses.
//
// The addresses may be strings or lists of bytes.
CompareIP!: _ @stdlib(func(_~ip1: _, _~ip2: _) -> int)

// PathEscape escapes the string so it can be safely placed inside a URL path
// segment, replacing special characters (including /) with %XX sequences as
// needed.
PathEscape!: _ @stdlib(func(_~s: string) -> string)

// PathUnescape does the inverse transformation of PathEscape, converting each
// 3-byte encoded substring of the form "%AB" into the hex-decoded byte 0xAB.
// It returns an error if any % is not followed by two hexadecimal digits.
//
// PathUnescape is identical to QueryUnescape except that it does not unescape
// '+' to ' ' (space).
PathUnescape!: _ @stdlib(func(_~s: string) -> string)

// QueryEscape escapes the string so it can be safely placed inside a URL
// query.
QueryEscape!: _ @stdlib(func(_~s: string) -> string)

// QueryUnescape does the inverse transformation of QueryEscape, converting
// each 3-byte encoded substring of the form "%AB" into the hex-decoded byte
// 0xAB. It returns an error if any % is not followed by two hexadecimal
// digits.
QueryUnescape!: _ @stdlib(func(_~s: string) -> string)

// URL validates that s is a valid relative or absolute URL.
// Note: this does also allow non-ASCII characters.
URL!: _ @stdlib(validator(string))

// AbsURL validates that s is an absolute URL.
// Note: this does also allow non-ASCII characters.
AbsURL!: _ @stdlib(validator(string))
