// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

// Package base64 implements base64 encoding as specified by RFC 4648.
package base64

// EncodedLen returns the length in bytes of the base64 encoding
// of an input buffer of length n. Encoding needs to be set to null
// as only StdEncoding is supported for now.
EncodedLen!: _ @stdlib(func(_~encoding: _, _~n: int) -> int)

// DecodedLen returns the maximum length in bytes of the decoded data
// corresponding to n bytes of base64-encoded data. Encoding needs to be set to
// null as only StdEncoding is supported for now.
DecodedLen!: _ @stdlib(func(_~encoding: _, _~x: int) -> int)

// Encode returns the base64 encoding of src. Encoding needs to be set to null
// as only StdEncoding is supported for now.
Encode!: _ @stdlib(func(_~encoding: _, _~src: bytes|string) -> string)

// Decode returns the bytes represented by the base64 string s. Encoding needs
// to be set to null as only StdEncoding is supported for now.
Decode!: _ @stdlib(func(_~encoding: _, _~s: string) -> bytes|string)
