// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package sha1

// The size of a SHA-1 checksum in bytes.
Size: 20

// The blocksize of SHA-1 in bytes.
BlockSize: 64

// Sum returns the SHA-1 checksum of the data.
Sum!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)
