// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package sha256

// The size of a SHA256 checksum in bytes.
Size: 32

// The size of a SHA224 checksum in bytes.
Size224: 28

// The blocksize of SHA256 and SHA224 in bytes.
BlockSize: 64

// Sum256 returns the SHA256 checksum of the data.
Sum256!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)

// Sum224 returns the SHA224 checksum of the data.
Sum224!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)
