// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package tabwriter

// Write formats text in columns. See golang.org/pkg/text/tabwriter for more
// info.
Write!: _ @stdlib(func(_~data: _) -> string)
