// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package csv

// Encode encode the given list of lists to CSV.
Encode!: _ @stdlib(func(_~x: _) -> string)

// Decode reads in a csv into a list of lists.
Decode!: _ @stdlib(func(_~r: bytes|string) -> [...])
