// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package template

// Execute executes a Go-style template.
Execute!: _ @stdlib(func(_~templ: string, _~data: _) -> string)

// HTMLEscape returns the escaped HTML equivalent of the plain text data s.
HTMLEscape!: _ @stdlib(func(_~s: string) -> string)

// JSEscape returns the escaped JavaScript equivalent of the plain text data s.
JSEscape!: _ @stdlib(func(_~s: string) -> string)
