// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package toml

// Marshal returns the TOML encoding of v.
Marshal!: _ @stdlib(func(_~v: _) -> string)

// Unmarshal parses the TOML to a CUE expression.
Unmarshal!: _ @stdlib(func(_~data: bytes|string) -> _)
