// Code generated by "stringer -type=Token,RelPos -linecomment -output=stringer_gen.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[ATTRIBUTE-3]
	_ = x[literalBeg-4]
	_ = x[IDENT-5]
	_ = x[INT-6]
	_ = x[FLOAT-7]
	_ = x[STRING-8]
	_ = x[INTERPOLATION-9]
	_ = x[BOTTOM-10]
	_ = x[literalEnd-11]
	_ = x[operatorBeg-12]
	_ = x[ADD-13]
	_ = x[SUB-14]
	_ = x[MUL-15]
	_ = x[POW-16]
	_ = x[QUO-17]
	_ = x[AND-18]
	_ = x[OR-19]
	_ = x[LAND-20]
	_ = x[LOR-21]
	_ = x[BIND-22]
	_ = x[EQL-23]
	_ = x[LSS-24]
	_ = x[GTR-25]
	_ = x[NOT-26]
	_ = x[ARROW-27]
	_ = x[RARROW-28]
	_ = x[NEQ-29]
	_ = x[LEQ-30]
	_ = x[GEQ-31]
	_ = x[MAT-32]
	_ = x[NMAT-33]
	_ = x[LPAREN-34]
	_ = x[LBRACK-35]
	_ = x[LBRACE-36]
	_ = x[COMMA-37]
	_ = x[PERIOD-38]
	_ = x[ELLIPSIS-39]
	_ = x[RPAREN-40]
	_ = x[RBRACK-41]
	_ = x[RBRACE-42]
	_ = x[SEMICOLON-43]
	_ = x[COLON-44]
	_ = x[OPTION-45]
	_ = x[TILDE-46]
	_ = x[operatorEnd-47]
	_ = x[keywordBeg-48]
	_ = x[IF-49]
	_ = x[ELSE-50]
	_ = x[FOR-51]
	_ = x[IN-52]
	_ = x[LET-53]
	_ = x[TRY-54]
	_ = x[FALLBACK-55]
	_ = x[OTHERWISE-56]
	_ = x[FUNC-57]
	_ = x[TRUE-58]
	_ = x[FALSE-59]
	_ = x[NULL-60]
	_ = x[keywordEnd-61]
}

const _Token_name = "ILLEGALEOFCOMMENTATTRIBUTEliteralBegIDENTINTFLOATSTRINGINTERPOLATION_|_literalEndoperatorBeg+-*^/&|&&||===<>!<-->!=<=>==~!~([{,....)]};:?~operatorEndkeywordBegifelseforinlettryfallbackotherwisefunctruefalsenullkeywordEnd"

var _Token_index = [...]uint8{0, 7, 10, 17, 26, 36, 41, 44, 49, 55, 68, 71, 81, 92, 93, 94, 95, 96, 97, 98, 99, 101, 103, 104, 106, 107, 108, 109, 111, 113, 115, 117, 119, 121, 123, 124, 125, 126, 127, 128, 131, 132, 133, 134, 135, 136, 137, 138, 149, 159, 161, 165, 168, 170, 173, 176, 184, 193, 197, 201, 206, 210, 220}

func (i Token) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Token_index)-1 {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[idx]:_Token_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoRelPos-0]
	_ = x[Elided-1]
	_ = x[NoSpace-2]
	_ = x[Blank-3]
	_ = x[Newline-4]
	_ = x[NewSection-5]
}

const _RelPos_name = "invalidelidednospaceblanknewlinesection"

var _RelPos_index = [...]uint8{0, 7, 13, 20, 25, 32, 39}

func (i RelPos) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RelPos_index)-1 {
		return "RelPos(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RelPos_name[_RelPos_index[idx]:_RelPos_index[idx+1]]
}
