// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

// Package uuid defines functionality for creating UUIDs as defined in RFC 4122.
//
// Currently only Version 5 (SHA1) and Version 3 (MD5) are supported.
package uuid

// Valid ensures that s is a valid UUID which would be accepted by Parse.
Valid!: _ @stdlib(validator(string))

// Parse decodes s into a UUID or returns an error. Both the standard UUID forms
// of xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and
// urn:uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx are decoded as well as the
// Microsoft encoding {xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx} and the raw hex
// encoding: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Parse!: _ @stdlib(func(_~s: string) -> string)

// URN reports the canonical URN of a UUID.
URN!: _ @stdlib(func(_~x: string) -> string)

// FromInt creates a UUID from an integer.
//
// 	DNS:  uuid.FromInt(0x6ba7b810_9dad_11d1_80b4_00c04fd430c8)
FromInt!: _ @stdlib(func(_~i: int) -> string)

// ToInt represents a UUID string as a 128-bit value.
ToInt!: _ @stdlib(func(_~x: string) -> int)

// Variant reports the UUID variant.
Variant!: _ @stdlib(func(_~x: string) -> int)

// Version reports the UUID version.
Version!: _ @stdlib(func(_~x: string) -> int)

// SHA1 generates a version 5 UUID based on the supplied name space and data.
SHA1!: _ @stdlib(func(_~space: string, _~data: bytes|string) -> string)

// MD5 generates a version 3 UUID based on the supplied name space and data.
// Use SHA1 instead if you can.
MD5!: _ @stdlib(func(_~space: string, _~data: bytes|string) -> string)

// Predefined namespaces
ns: {
	DNS:  "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
	URL:  "6ba7b811-9dad-11d1-80b4-00c04fd430c8"
	OID:  "6ba7b812-9dad-11d1-80b4-00c04fd430c8"
	X500: "6ba7b814-9dad-11d1-80b4-00c04fd430c8"
	Nil:  "00000000-0000-0000-0000-000000000000"
}

// Invalid UUID
variants: Invalid: 0
// The variant specified in RFC4122
variants: RFC4122: 1
// Reserved, NCS backward compatibility.
variants: Reserved: 2
// Reserved, Microsoft Corporation backward compatibility.
variants: Microsoft: 3
// Reserved for future definition.
variants: Future: 4
