// Code generated by cuelang.org/go/internal/filetypes/generate.go from types.cue. DO NOT EDIT.

//go:build !cuebootstrap

package filetypes

func newTagTypes() map[string]TagType {
	return map[string]TagType{
		"allSchemas":           TagSubsidiaryBool,
		"auto":                 TagTopLevel,
		"binary":               TagTopLevel,
		"code":                 TagTopLevel,
		"compact":              TagSubsidiaryBool,
		"cue":                  TagTopLevel,
		"dag":                  TagTopLevel,
		"data":                 TagTopLevel,
		"go":                   TagTopLevel,
		"graph":                TagTopLevel,
		"indentSequences":      TagSubsidiaryBool,
		"ini":                  TagTopLevel,
		"json":                 TagTopLevel,
		"jsonl":                TagTopLevel,
		"jsonschema":           TagTopLevel,
		"koala":                TagSubsidiaryBool,
		"lang":                 TagSubsidiaryString,
		"openOnlyWhenExplicit": TagSubsidiaryBool,
		"openapi":              TagTopLevel,
		"pb":                   TagTopLevel,
		"proto":                TagTopLevel,
		"schema":               TagTopLevel,
		"strict":               TagSubsidiaryBool,
		"strictFeatures":       TagSubsidiaryBool,
		"strictKeywords":       TagSubsidiaryBool,
		"text":                 TagTopLevel,
		"textproto":            TagTopLevel,
		"toml":                 TagTopLevel,
		"xml":                  TagTopLevel,
		"yaml":                 TagTopLevel,
	}
}

func newBuiltinRegistry() *registryData {
	return &registryData{
		base: [NumModes]*entry{
			Input: {
				aspects: [numAspects]bval{aAttributes: dtrue, aCycles: dtrue, aData: dtrue, aDocs: dtrue, aReferences: dtrue},
			},
			Export: {
				aspects: [numAspects]bval{aAttributes: dfalse, aCycles: dtrue, aData: dtrue, aDocs: dfalse, aReferences: dtrue},
			},
			Def: {
				aspects: [numAspects]bval{aAttributes: dtrue, aCycles: dtrue, aData: dtrue, aDocs: dtrue, aReferences: dtrue},
			},
			Eval: {
				aspects: [numAspects]bval{aAttributes: dfalse, aCycles: dtrue, aData: dtrue, aDocs: dfalse, aReferences: dtrue},
			},
		},
		extensions: [NumModes]map[string]*entry{
			Input: {
				"-": {
					encoding: dstrNot("cue", ""),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".cue": {
					encoding: cstr("cue"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       cstr("code"),
					interpretation: cstr(""),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					tags: map[string]sval{
						"lang": cstr("go"),
					},
				},
				".ini": {
					encoding:       cstr("ini"),
					interpretation: dstr("auto"),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".json": {
					encoding:       cstr("json"),
					interpretation: dstr("auto"),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ldjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ndjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".proto": {
					encoding: cstr("proto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textpb": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textproto": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".toml": {
					encoding:       cstr("toml"),
					interpretation: dstr("auto"),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".txt": {
					encoding: cstr("text"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".wasm": {
					encoding: cstr("binary"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".xml": {
					encoding:       cstr("xml"),
					interpretation: dstr("auto"),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding:       cstr("yaml"),
					interpretation: dstr("auto"),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding:       cstr("yaml"),
					interpretation: dstr("auto"),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
			Export: {
				"-": {
					encoding: dstrNot("json", ""),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".cue": {
					encoding: cstr("cue"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       cstr("code"),
					interpretation: cstr(""),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					tags: map[string]sval{
						"lang": cstr("go"),
					},
				},
				".ini": {
					encoding: cstr("ini"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".json": {
					encoding: cstr("json"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ldjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ndjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".proto": {
					encoding: cstr("proto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textpb": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textproto": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".toml": {
					encoding: cstr("toml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".txt": {
					encoding: cstr("text"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".wasm": {
					encoding: cstr("binary"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".xml": {
					encoding: cstr("xml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding: cstr("yaml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding: cstr("yaml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
			Def: {
				"-": {
					encoding: dstrNot("cue", ""),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".cue": {
					encoding: cstr("cue"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       cstr("code"),
					interpretation: cstr(""),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					tags: map[string]sval{
						"lang": cstr("go"),
					},
				},
				".ini": {
					encoding: cstr("ini"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".json": {
					encoding: cstr("json"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ldjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ndjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".proto": {
					encoding: cstr("proto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textpb": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textproto": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".toml": {
					encoding: cstr("toml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".txt": {
					encoding: cstr("text"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".wasm": {
					encoding: cstr("binary"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".xml": {
					encoding: cstr("xml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding: cstr("yaml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding: cstr("yaml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
			Eval: {
				"-": {
					encoding: dstrNot("cue", ""),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".cue": {
					encoding: cstr("cue"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".go": {
					encoding:       cstr("code"),
					interpretation: cstr(""),
					aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					tags: map[string]sval{
						"lang": cstr("go"),
					},
				},
				".ini": {
					encoding: cstr("ini"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".json": {
					encoding: cstr("json"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"compact": dfalse,
					},
				},
				".jsonl": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ldjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".ndjson": {
					encoding: cstr("jsonl"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".proto": {
					encoding: cstr("proto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textpb": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".textproto": {
					encoding: cstr("textproto"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".toml": {
					encoding: cstr("toml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".txt": {
					encoding: cstr("text"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".wasm": {
					encoding: cstr("binary"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				},
				".xml": {
					encoding: cstr("xml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"koala": dfalse,
					},
				},
				".yaml": {
					encoding: cstr("yaml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
				".yml": {
					encoding: cstr("yaml"),
					aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					boolTags: map[string]bval{
						"indentSequences": dtrue,
					},
				},
			},
		},
		encodings: [NumModes]map[string]*entry{
			Input: {
				"binary": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"binarypb": {
					encoding: cstr("binarypb"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"code": {
					form:    dstrDom("schema", "final", "graph", "schema"),
					aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse},
				},
				"cue": {
					alts: []*entry{
						{
							form:    dstrDom("schema", "final", "graph", "schema"),
							aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse},
						},
						{
							form:    dstrDom("schema", "final", "graph", "schema"),
							aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse},
						},
						{
							aspects: [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue, aStream: cfalse},
						},
					},
				},
				"ini": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"json": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aAttributes: cfalse, aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aDocs: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: dfalse},
				},
				"jsonl": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: ctrue},
				},
				"proto": {
					encoding: cstr("proto"),
					form:     dstrDom("schema", "final", "graph", "schema"),
					aspects:  [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				},
				"text": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"textproto": {
					encoding: cstr("textproto"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"toml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"xml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"yaml": {
					form:    dstrDom("graph", "dag", "data", "graph"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: dtrue, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: dtrue},
				},
			},
			Export: {
				"binary": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"binarypb": {
					encoding: cstr("binarypb"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"code": {
					form:    dstrDom("schema", "final", "graph", "schema"),
					aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse},
				},
				"cue": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"ini": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"json": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aAttributes: cfalse, aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aDocs: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: dfalse},
				},
				"jsonl": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: ctrue},
				},
				"proto": {
					encoding: cstr("proto"),
					form:     dstrDom("schema", "final", "graph", "schema"),
					aspects:  [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				},
				"text": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"textproto": {
					encoding: cstr("textproto"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"toml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"xml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"yaml": {
					form:    dstrDom("graph", "dag", "data", "graph"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: dtrue, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: dtrue},
				},
			},
			Def: {
				"binary": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"binarypb": {
					encoding: cstr("binarypb"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"code": {
					form:    dstrDom("schema", "final", "graph", "schema"),
					aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse},
				},
				"cue": {
					form:    dstrDom("schema", "final", "graph", "schema"),
					aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse},
				},
				"ini": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"json": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aAttributes: cfalse, aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aDocs: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: dfalse},
				},
				"jsonl": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: ctrue},
				},
				"proto": {
					encoding: cstr("proto"),
					form:     dstrDom("schema", "final", "graph", "schema"),
					aspects:  [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				},
				"text": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"textproto": {
					encoding: cstr("textproto"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"toml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"xml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"yaml": {
					form:    dstrDom("graph", "dag", "data", "graph"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: dtrue, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: dtrue},
				},
			},
			Eval: {
				"binary": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"binarypb": {
					encoding: cstr("binarypb"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"code": {
					form:    dstrDom("schema", "final", "graph", "schema"),
					aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: cfalse},
				},
				"cue": {
					form:    cstr("final"),
					aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: cfalse},
				},
				"ini": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"json": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aAttributes: cfalse, aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aDocs: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: dfalse},
				},
				"jsonl": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: ctrue},
				},
				"proto": {
					encoding: cstr("proto"),
					form:     dstrDom("schema", "final", "graph", "schema"),
					aspects:  [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				},
				"text": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"textproto": {
					encoding: cstr("textproto"),
					form:     cstr("data"),
					aspects:  [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"toml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"xml": {
					form:    cstr("data"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: cfalse},
				},
				"yaml": {
					form:    dstrDom("graph", "dag", "data", "graph"),
					aspects: [numAspects]bval{aConstraints: cfalse, aCycles: dtrue, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: dtrue},
				},
			},
		},
		tagInfo: map[string]*entry{
			"auto": {
				encoding:       dstrNot("json", ""),
				interpretation: cstr("auto"),
				form:           dstrDom("schema", "final", "graph", "schema"),
				aspects:        [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
			},
			"binary": {
				encoding: cstr("binary"),
				form:     cstr("data"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"code": {
				encoding:       cstr("code"),
				interpretation: cstr(""),
				aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				tags: map[string]sval{
					"lang": dstr(""),
				},
			},
			"cue": {
				encoding: cstr("cue"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				boolTags: map[string]bval{
					"compact": dfalse,
				},
			},
			"dag": {
				form:    cstr("dag"),
				aspects: [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"data": {
				form:    cstr("data"),
				aspects: [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"go": {
				encoding:       cstr("code"),
				interpretation: cstr(""),
				aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				tags: map[string]sval{
					"lang": cstr("go"),
				},
			},
			"graph": {
				form:    cstr("graph"),
				aspects: [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"ini": {
				encoding: cstr("ini"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"json": {
				encoding: cstr("json"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				boolTags: map[string]bval{
					"compact": dfalse,
				},
			},
			"jsonl": {
				encoding: cstr("jsonl"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"jsonschema": {
				encoding:       dstrNot("json", ""),
				interpretation: cstr("jsonschema"),
				form:           dstrDom("schema", "final", "graph", "schema"),
				aspects:        [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				boolTags: map[string]bval{
					"openOnlyWhenExplicit": dfalse,
					"strict":               dfalse,
					"strictFeatures":       rbool("strict"),
					"strictKeywords":       rbool("strict"),
				},
			},
			"openapi": {
				encoding:       dstrNot("json", ""),
				interpretation: cstr("openapi"),
				form:           dstrDom("schema", "final", "graph", "schema"),
				aspects:        [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				boolTags: map[string]bval{
					"allSchemas":     dfalse,
					"strict":         dfalse,
					"strictFeatures": rbool("strict"),
					"strictKeywords": rbool("strict"),
				},
			},
			"pb": {
				alts: []*entry{
					{
						encoding:       cstr("binarypb"),
						interpretation: cstr(""),
						aspects:        [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
					},
					{
						encoding:       cstr("binarypb"),
						interpretation: cstr(""),
					},
					{
						encoding:       strNot("binarypb"),
						interpretation: cstr("pb"),
					},
				},
			},
			"proto": {
				encoding: cstr("proto"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"schema": {
				form:    cstr("schema"),
				aspects: [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"text": {
				encoding: cstr("text"),
				form:     cstr("data"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"textproto": {
				encoding: cstr("textproto"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"toml": {
				encoding: cstr("toml"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
			},
			"xml": {
				encoding: cstr("xml"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				boolTags: map[string]bval{
					"koala": dfalse,
				},
			},
			"yaml": {
				encoding: cstr("yaml"),
				aspects:  [numAspects]bval{aCycles: dtrue, aData: dtrue, aReferences: dtrue},
				boolTags: map[string]bval{
					"indentSequences": dtrue,
				},
			},
		},
		forms: map[string]*entry{
			"dag": {
				form:    strDom("dag", "data"),
				aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue},
			},
			"data": {
				form:    cstr("data"),
				aspects: [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse},
			},
			"final": {
				form:    cstr("final"),
				aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue, aStream: dfalse},
			},
			"graph": {
				form:    dstrDom("graph", "dag", "data", "graph"),
				aspects: [numAspects]bval{aConstraints: cfalse, aCycles: dtrue, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: dtrue},
			},
			"schema": {
				form:    dstrDom("schema", "final", "graph", "schema"),
				aspects: [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
			},
		},
		interps: map[string]*entry{
			"auto": {
				interpretation: cstr("auto"),
				form:           dstrDom("schema", "final", "graph", "schema"),
				aspects:        [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
			},
			"jsonschema": {
				encoding:       dstrNot("json", ""),
				interpretation: cstr("jsonschema"),
				form:           dstrDom("schema", "final", "graph", "schema"),
				aspects:        [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				boolTags: map[string]bval{
					"openOnlyWhenExplicit": dfalse,
					"strict":               dfalse,
					"strictFeatures":       rbool("strict"),
					"strictKeywords":       rbool("strict"),
				},
			},
			"openapi": {
				encoding:       dstrNot("json", ""),
				interpretation: cstr("openapi"),
				form:           dstrDom("schema", "final", "graph", "schema"),
				aspects:        [numAspects]bval{aConstraints: dtrue, aCycles: dtrue, aData: dtrue, aDefinitions: dtrue, aIncomplete: dtrue, aImports: dtrue, aKeepDefaults: dtrue, aOptional: dtrue, aReferences: dtrue, aStream: dfalse},
				boolTags: map[string]bval{
					"allSchemas":     dfalse,
					"strict":         dfalse,
					"strictFeatures": rbool("strict"),
					"strictKeywords": rbool("strict"),
				},
			},
			"pb": {
				interpretation: cstr("pb"),
				form:           cstr("data"),
				aspects:        [numAspects]bval{aConstraints: cfalse, aCycles: cfalse, aData: ctrue, aDefinitions: cfalse, aIncomplete: cfalse, aImports: cfalse, aKeepDefaults: cfalse, aOptional: cfalse, aReferences: cfalse, aStream: ctrue},
			},
		},
	}
}
