// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package bits

// Lsh sets and returns x shifted left by n bits.
Lsh!: _ @stdlib(func(_~x: int, _~n: int) -> int)

// Rsh sets and returns x shifted right by n bits.
Rsh!: _ @stdlib(func(_~x: int, _~n: int) -> int)

// At returns the value of the i'th bit of x.
At!: _ @stdlib(func(_~x: int, _~i: int) -> int)

// Set sets and returns x with x's i'th bit set to b (0 or 1).
// That is, if b is 1 Set returns x with its i'th bit set;
// if b is 0 Set returns x with its i'th bit cleared.
Set!: _ @stdlib(func(_~x: int, _~i: int, _~bit: int) -> int)

// And sets and returns a to the bitwise "and" of a and b.
And!: _ @stdlib(func(_~a: int, _~b: int) -> int)

// Or sets and returns a to the bitwise "or" of a and b (a | b in Go).
Or!: _ @stdlib(func(_~a: int, _~b: int) -> int)

// Xor sets and returns a to the bitwise xor of a and b (a ^ b in Go).
Xor!: _ @stdlib(func(_~a: int, _~b: int) -> int)

// Clear sets and returns a to the bitwise "and not" of a and b (a &^ b in Go).
Clear!: _ @stdlib(func(_~a: int, _~b: int) -> int)

// OnesCount returns the number of one bits ("population count") in x.
OnesCount!: _ @stdlib(func(_~x: int) -> int)

// Len returns the length of the absolute value of x in bits. The bit length
// of 0 is 0.
Len!: _ @stdlib(func(_~x: int) -> int)
