// Code generated by "stringer -type=ArcType,vertexStatus,ErrorCode,Op,runMode,defIDType -trimprefix=Arc -linecomment -output=stringer_gen.go"; DO NOT EDIT.

package adt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArcMember-0]
	_ = x[ArcRequired-1]
	_ = x[ArcOptional-2]
	_ = x[ArcPending-3]
	_ = x[ArcNotPresent-4]
}

const _ArcType_name = "MemberRequiredOptionalPendingNotPresent"

var _ArcType_index = [...]uint8{0, 6, 14, 22, 29, 39}

func (i ArcType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ArcType_index)-1 {
		return "ArcType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArcType_name[_ArcType_index[idx]:_ArcType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unprocessed-0]
	_ = x[evaluating-1]
	_ = x[partial-2]
	_ = x[conjuncts-3]
	_ = x[finalized-4]
}

const _vertexStatus_name = "unprocessedevaluatingpartialconjunctsfinalized"

var _vertexStatus_index = [...]uint8{0, 11, 21, 28, 37, 46}

func (i vertexStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_vertexStatus_index)-1 {
		return "vertexStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _vertexStatus_name[_vertexStatus_index[idx]:_vertexStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EvalError-0]
	_ = x[UserError-1]
	_ = x[LegacyUserError-2]
	_ = x[StructuralCycleError-3]
	_ = x[IncompleteError-4]
	_ = x[CycleError-5]
}

const _ErrorCode_name = "evaluseruserstructural_cycleincompletecycle"

var _ErrorCode_index = [...]uint8{0, 4, 8, 12, 28, 38, 43}

func (i ErrorCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrorCode_index)-1 {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[idx]:_ErrorCode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoOp-0]
	_ = x[AndOp-1]
	_ = x[OrOp-2]
	_ = x[SelectorOp-3]
	_ = x[IndexOp-4]
	_ = x[SliceOp-5]
	_ = x[CallOp-6]
	_ = x[BoolAndOp-7]
	_ = x[BoolOrOp-8]
	_ = x[EqualOp-9]
	_ = x[NotOp-10]
	_ = x[NotEqualOp-11]
	_ = x[LessThanOp-12]
	_ = x[LessEqualOp-13]
	_ = x[GreaterThanOp-14]
	_ = x[GreaterEqualOp-15]
	_ = x[MatchOp-16]
	_ = x[NotMatchOp-17]
	_ = x[AddOp-18]
	_ = x[SubtractOp-19]
	_ = x[MultiplyOp-20]
	_ = x[FloatQuotientOp-21]
	_ = x[InterpolationOp-22]
	_ = x[SpreadOp-23]
}

const _Op_name = "NoOp&|.[][:]()&&||==!!=<<=>>==~!~+-*/\\()..."

var _Op_index = [...]uint8{0, 4, 5, 6, 7, 9, 12, 14, 16, 18, 20, 21, 23, 24, 26, 27, 29, 31, 33, 34, 35, 36, 37, 40, 43}

func (i Op) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Op_index)-1 {
		return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Op_name[_Op_index[idx]:_Op_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ignore-1]
	_ = x[attemptOnly-2]
	_ = x[yield-3]
	_ = x[finalize-4]
}

const _runMode_name = "ignoreattemptOnlyyieldfinalize"

var _runMode_index = [...]uint8{0, 6, 17, 22, 30}

func (i runMode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_runMode_index)-1 {
		return "runMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _runMode_name[_runMode_index[idx]:_runMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[defIDTypeUnknown-0]
	_ = x[defEmbedding-1]
	_ = x[defReference-2]
	_ = x[defStruct-3]
}

const _defIDType_name = "*EDS"

var _defIDType_index = [...]uint8{0, 1, 2, 3, 4}

func (i defIDType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_defIDType_index)-1 {
		return "defIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _defIDType_name[_defIDType_index[idx]:_defIDType_index[idx+1]]
}
