// Copyright 2018 The CUE Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build ignore

// gen.go generates the pkg.go files inside the packages under the pkg
// directory, as well as the pkg.cue files alongside them which
// describe each package's API.
//
// Be sure to also update an entry in pkg/pkg.go, if so desired.
package main

import (
	"bytes"
	"cmp"
	_ "embed"
	"flag"
	"fmt"
	goast "go/ast"
	"go/constant"
	"go/format"
	"go/token"
	"go/types"
	"io/fs"
	"log"
	"math/big"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"

	"cuelang.org/go/cue/ast"
	cueformat "cuelang.org/go/cue/format"
	"cuelang.org/go/cue/parser"
	"cuelang.org/go/internal"
)

const pkgParent = "cuelang.org/go/pkg"

func main() {
	flag.Parse()
	log.SetFlags(log.Lshortfile)
	log.SetOutput(os.Stdout)

	cfg := &packages.Config{Mode: packages.NeedName | packages.NeedFiles | packages.NeedTypes | packages.NeedSyntax}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		fmt.Fprintf(os.Stderr, "load: %v\n", err)
		os.Exit(1)
	}
	// Errors in the root pkg package are tolerated: it embeds the
	// generated pkg.cue files, so it cannot load in a tree where they
	// have not yet been generated, and nothing is generated from it.
	errCount := 0
	for _, pkg := range pkgs {
		if pkg.PkgPath == pkgParent {
			continue
		}
		for _, err := range pkg.Errors {
			fmt.Fprintln(os.Stderr, err)
			errCount++
		}
	}
	if errCount > 0 {
		os.Exit(1)
	}
	// Sort the Go packages by import path; otherwise adding a new builtin package
	// puts it at the very end of the list the first time it is getting added to register.go,
	// as it's not imported by the root package yet. Sorting ensures consistent output.
	slices.SortFunc(pkgs, func(a, b *packages.Package) int {
		return cmp.Compare(a.PkgPath, b.PkgPath)
	})

	regBuf := new(bytes.Buffer)
	fmt.Fprintf(regBuf, "// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(regBuf, "package pkg\n\n")
	fmt.Fprintf(regBuf, "import (\n")
	written := make(map[string]bool)
	for _, pkg := range pkgs {
		switch {
		case pkg.PkgPath == pkgParent:
			// The pkg package itself should not be generated.
		case strings.Contains(pkg.PkgPath, "/internal"):
			// Internal packages are not for public use.
		default:
			fmt.Fprintf(regBuf, "\t_ %q\n", pkg.PkgPath)
			if err := generate(pkg, written); err != nil {
				log.Fatalf("%s: %v", pkg, err)
			}
		}
	}
	fmt.Fprintf(regBuf, ")\n")
	if err := os.WriteFile("register.go", regBuf.Bytes(), 0o666); err != nil {
		log.Fatal(err)
	}
	if err := pruneGeneratedCUE(written); err != nil {
		log.Fatal(err)
	}
}

// An emitter accumulates one generated file for a standard library
// package. The package's members are reported to it in source order,
// followed by the package's supplemental CUE file, if it has one.
type emitter interface {
	// constant records an exported constant and its rendered value.
	constant(obj *types.Const, value string)

	// function records an exported function usable as a builtin.
	function(fn *types.Func)

	// supplementalCUE records the package's supplemental CUE file,
	// maintained alongside its Go sources; expr is its parsed form (a
	// single expression wrapping the file's declarations), src their
	// verbatim source.
	supplementalCUE(expr ast.Expr, src []byte) error

	// close formats the accumulated file and writes it to the
	// package's directory.
	close() error
}

// emitters broadcasts each call to every emitter in the list.
type emitters []emitter

func (es emitters) constant(obj *types.Const, value string) {
	for _, e := range es {
		e.constant(obj, value)
	}
}

func (es emitters) function(fn *types.Func) {
	for _, e := range es {
		e.function(fn)
	}
}

func (es emitters) supplementalCUE(expr ast.Expr, src []byte) error {
	for _, e := range es {
		if err := e.supplementalCUE(expr, src); err != nil {
			return err
		}
	}
	return nil
}

func (es emitters) close() error {
	for _, e := range es {
		if err := e.close(); err != nil {
			return err
		}
	}
	return nil
}

// generate writes the generated files for a package; each pkg.cue
// file written is recorded in written.
func generate(pkg *packages.Package, written map[string]bool) error {
	// go/packages supports multiple build systems, including some which don't keep
	// a Go package entirely within a single directory.
	// However, we know for certain that CUE uses modules, so it is the case here.
	// We can figure out the directory from the first Go file.
	pkgDir := filepath.Dir(pkg.GoFiles[0])
	cuePkg := strings.TrimPrefix(pkg.PkgPath, pkgParent+"/")

	params := headerParams{
		GoPkg:  pkg.Name,
		CUEPkg: cuePkg,
	}
	// As a special case, the "tool" package cannot be imported from CUE.
	skipRegister := params.CUEPkg == "tool"
	if skipRegister {
		params.CUEPkg = ""
	}

	if doc, err := os.ReadFile(filepath.Join(pkgDir, "doc.txt")); err == nil {
		defs, err := os.ReadFile(filepath.Join(pkgDir, pkg.Name+".cue"))
		if err != nil {
			return err
		}
		i := bytes.Index(defs, []byte("package "+pkg.Name))
		defs = defs[i+len("package "+pkg.Name)+1:]
		defs = bytes.TrimRight(defs, "\n")
		defs = bytes.ReplaceAll(defs, []byte("\n"), []byte("\n//\t"))
		params.PackageDoc = string(doc)
		params.PackageDefs = string(defs)
	}

	var emits emitters
	// TODO remove this special case. Currently the path pkg.go file
	// cannot be generated automatically but that will be possible when
	// we can attach arbitrary signatures to builtin functions. The CUE
	// definition file is generated like any other package's.
	if pkg.PkgPath != "cuelang.org/go/pkg/path" {
		goEmit, err := newGoEmitter(pkgDir, pkg.PkgPath, params, !skipRegister)
		if err != nil {
			return err
		}
		emits = append(emits, goEmit)
	}
	if !skipRegister {
		emits = append(emits, newCUEEmitter(pkgDir, cuePkg, pkg, params.PackageDoc, written))

		emitMembers(pkg, cuePkg, emits)

		expr, src, err := loadSupplementalCUE(pkgDir)
		if err != nil {
			return fmt.Errorf("error processing %s: %v", cuePkg, err)
		}
		if expr != nil {
			if err := emits.supplementalCUE(expr, src); err != nil {
				return err
			}
		}
	}
	return emits.close()
}

var (
	typeError = types.Universe.Lookup("error").Type()
	typeByte  = types.Universe.Lookup("byte").Type()
)

// validatorType is the type of the result by which a builtin declares
// that it is intended for use as a validator; see
// [cuelang.org/go/internal/pkg.Validator]. It aliases bool.
const validatorType = "cuelang.org/go/internal/pkg.Validator"

// emitMembers feeds the package's exported constants and functions,
// in source order, to the emitter.
func emitMembers(pkg *packages.Package, cuePkgPath string, e emitter) {
	// We sort the objects by their original source code position.
	// Otherwise, go/types defaults to sorting by name strings.
	// We could remove this code if we were fine with sorting by name.
	scope := pkg.Types.Scope()
	type objWithPos struct {
		obj types.Object
		pos token.Position
	}
	var objs []objWithPos
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		objs = append(objs, objWithPos{obj, pkg.Fset.Position(obj.Pos())})
	}
	slices.SortFunc(objs, func(a, b objWithPos) int {
		if c := cmp.Compare(a.pos.Filename, b.pos.Filename); c != 0 {
			return c
		}
		return cmp.Compare(a.pos.Line, b.pos.Line)
	})

	for _, obj := range objs {
		obj := obj.obj // no longer need the token.Position
		if !obj.Exported() {
			continue
		}
		// TODO: support type declarations.
		switch obj := obj.(type) {
		case *types.Const:
			var value string
			switch v := obj.Val(); v.Kind() {
			case constant.Bool, constant.Int, constant.String:
				// TODO: convert octal numbers
				value = v.ExactString()
			case constant.Float:
				var rat big.Rat
				rat.SetString(v.ExactString())
				var float big.Float
				float.SetRat(&rat)
				value = float.Text('g', -1)
			default:
				fmt.Printf("Dropped entry %s.%s (%T: %v)\n", cuePkgPath, obj.Name(), v.Kind(), v.ExactString())
				continue
			}
			e.constant(obj, value)
		case *types.Func:
			sign := obj.Signature()
			if sign.Recv() != nil {
				continue
			}
			results := sign.Results()
			if results == nil || (results.Len() != 1 && results.At(1).Type() != typeError) {
				fmt.Printf("Dropped func %s.%s: must have one return value or a value and an error %v\n", cuePkgPath, obj.Name(), sign)
				continue
			}
			e.function(obj)
		}
	}
}

// loadSupplementalCUE parses the directory's supplemental CUE file and
// returns its contents as an expression, typically a struct holding all
// of the file's declarations, along with the verbatim source of those
// declarations: everything following the package clause.
// If the directory has no such file, it returns (nil, nil, nil).
//
// It avoids the cue/load and cuecontext packages because they depend
// on the standard library which is what this command is generating -
// cyclic dependencies are undesirable in general.
func loadSupplementalCUE(dir string) (ast.Expr, []byte, error) {
	cuefiles, err := filepath.Glob(filepath.Join(dir, "*.cue"))
	if err != nil {
		return nil, nil, err
	}
	// The generated pkg.cue file is this generator's output, never
	// its input.
	cuefiles = slices.DeleteFunc(cuefiles, func(name string) bool {
		return filepath.Base(name) == "pkg.cue"
	})
	if len(cuefiles) == 0 {
		return nil, nil, nil
	}
	if len(cuefiles) > 1 {
		// Supporting multiple CUE files would require merging declarations.
		return nil, nil, fmt.Errorf("multiple CUE files not supported in this generator")
	}
	src, err := os.ReadFile(cuefiles[0])
	if err != nil {
		return nil, nil, err
	}
	file, err := parser.ParseFile(cuefiles[0], src)
	if err != nil {
		return nil, nil, err
	}
	clause, _ := internal.Package(file)
	if clause == nil {
		return nil, nil, fmt.Errorf("no package clause in %s", cuefiles[0])
	}
	decls := src[clause.End().Offset():]
	return internal.ToExpr(file), decls, nil
}

// pruneGeneratedCUE removes pkg.cue files that were not written by
// this run of the generator, left behind by packages that no longer
// exist.
func pruneGeneratedCUE(written map[string]bool) error {
	return filepath.WalkDir(".", func(filename string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || d.Name() != "pkg.cue" {
			return err
		}
		abs, err := filepath.Abs(filename)
		if err != nil {
			return err
		}
		if !written[abs] {
			return os.Remove(filename)
		}
		return nil
	})
}

type headerParams struct {
	GoPkg  string
	CUEPkg string

	PackageDoc  string
	PackageDefs string
}

var header = template.Must(template.New("").Parse(
	`// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

{{if .PackageDoc}}
{{.PackageDoc -}}
//     {{.PackageDefs}}
{{end -}}
package {{.GoPkg}}

{{if .CUEPkg -}}
import (
	"cuelang.org/go/internal/core/adt"
	"cuelang.org/go/internal/pkg"
)

func init() {
	pkg.Register({{printf "%q" .CUEPkg}}, p)
}

var _ = adt.TopKind // in case the adt package isn't used
{{end}}
`))

// A goEmitter generates a package's pkg.go file, which registers the
// package's builtins with the runtime.
type goEmitter struct {
	dir     string
	pkgPath string
	// registered is whether the package registers itself for import
	// from CUE; the "tool" package does not, and its pkg.go holds only
	// the file header.
	registered bool

	w           *bytes.Buffer
	cue         string // rendered CUE field holding the supplemental declarations
	first       bool
	nonConcrete bool
}

func newGoEmitter(dir, pkgPath string, params headerParams, registered bool) (*goEmitter, error) {
	g := &goEmitter{
		dir:        dir,
		pkgPath:    pkgPath,
		registered: registered,
		w:          &bytes.Buffer{},
		first:      true,
	}
	if err := header.Execute(g.w, params); err != nil {
		return nil, err
	}
	if registered {
		fmt.Fprintf(g.w, "var p = &pkg.Package{\nNative: []*pkg.Builtin{")
	}
	return g, nil
}

func (g *goEmitter) sep() {
	if g.first {
		g.first = false
		return
	}
	fmt.Fprint(g.w, ", ")
}

func (g *goEmitter) constant(obj *types.Const, value string) {
	g.sep()
	fmt.Fprintf(g.w, "{\nName: %q,\n Const: %q,\n}", obj.Name(), value)
}

// function emits a function's builtin implementation.
func (g *goEmitter) function(fn *types.Func) {
	g.nonConcrete = false
	sign := fn.Signature()
	params := sign.Params()
	results := sign.Results()

	g.sep()
	fmt.Fprintf(g.w, "{\n")
	defer fmt.Fprintf(g.w, "}")

	fmt.Fprintf(g.w, "Name: %q,\n", fn.Name())

	needCallContext := false
	args := []string{}
	vals := []string{}
	kind := []string{}
	for param := range params.Variables() {
		typ := param.Type()
		if typ.String() == "cuelang.org/go/internal/pkg.Schema" {
			needCallContext = true
		}
		methodName := g.callCtxtGetter(typ)
		argKind := g.adtKind(param.Type())
		vals = append(vals, fmt.Sprintf("c.%s(%d)", methodName, len(args)))
		args = append(args, param.Name())
		kind = append(kind, argKind)
	}

	fmt.Fprintf(g.w, "Params: []pkg.Param{\n")
	for _, k := range kind {
		fmt.Fprintf(g.w, "{Kind: %s},\n", k)
	}
	fmt.Fprintf(g.w, "\n},\n")

	fmt.Fprintf(g.w, "Result: %s,\n", g.adtKind(results.At(0).Type()))
	if g.nonConcrete {
		fmt.Fprintf(g.w, "NonConcrete: true,\n")
	}

	argList := strings.Join(args, ", ")
	valList := strings.Join(vals, ", ")
	init := ""
	if len(args) > 0 {
		init = fmt.Sprintf("%s := %s", argList, valList)
	}

	name := fn.Name()
	if needCallContext {
		argList = "c.OpContext(), " + argList

		// Main function is used for Godoc documentation. Once we have proper
		// CUE function signatures, we can remove these stubs.
		// NOTE: this will not work for scripts that are not cased. But this
		// is intended to be a temporary situation anyway.
		name = strings.ToLower(name[:1]) + name[1:]
	}

	fmt.Fprintf(g.w, "Func: func(c *pkg.CallCtxt) {")
	defer fmt.Fprintln(g.w, "},")
	fmt.Fprintln(g.w)
	if init != "" {
		fmt.Fprintln(g.w, init)
	}
	fmt.Fprintln(g.w, "if c.Do() {")
	defer fmt.Fprintln(g.w, "}")
	if results.Len() == 1 {
		fmt.Fprintf(g.w, "c.Ret = %s(%s)", name, argList)
	} else {
		fmt.Fprintf(g.w, "c.Ret, c.Err = %s(%s)", name, argList)
	}
}

// supplementalCUE renders the supplemental declarations as the
// package's CUE field, which the runtime mixes in with the native
// builtins.
func (g *goEmitter) supplementalCUE(expr ast.Expr, _ []byte) error {
	b, err := cueformat.Node(expr)
	if err != nil {
		return err
	}

	// Compact the CUE by removing empty lines. This requires re-formatting to align fields.
	// TODO(mvdan): provide a "compact" option in cue/format for this purpose?
	b = bytes.ReplaceAll(b, []byte("\n\n"), []byte("\n"))
	b, err = cueformat.Source(b)
	if err != nil {
		return err
	}
	b = bytes.TrimSpace(b) // no trailing newline

	// Try to use a Go string with backquotes, for readability.
	// If not possible due to cueSrc itself having backquotes,
	// use a single-line double-quoted string, removing tabs for brevity.
	// We don't use strconv.CanBackquote as it is for quoting as a single line.
	if cueSrc := string(b); !strings.Contains(cueSrc, "`") {
		g.cue = fmt.Sprintf("CUE: `%s`,\n", cueSrc)
	} else {
		cueSrc = strings.ReplaceAll(cueSrc, "\t", "")
		g.cue = fmt.Sprintf("CUE: %q,\n", cueSrc)
	}
	return nil
}

// close formats the accumulated Go source and writes it to pkg.go in
// the package's directory.
func (g *goEmitter) close() error {
	if g.registered {
		fmt.Fprintf(g.w, "},\n")
		g.w.WriteString(g.cue)
		fmt.Fprintf(g.w, "}\n")
	}
	b, err := format.Source(g.w.Bytes())
	if err != nil {
		fmt.Printf("go/format error on %s: %v\n", g.pkgPath, err)
		b = g.w.Bytes() // write the unformatted source
	}
	return os.WriteFile(filepath.Join(g.dir, "pkg.go"), b, 0o666)
}

// callCtxtGetter returns the name of the [cuelang.org/go/internal/pkg.CallCtxt] method
// which can be used to fetch a parameter of the given type.
func (g *goEmitter) callCtxtGetter(typ types.Type) string {
	switch typ := typ.(type) {
	case *types.Basic:
		return strings.Title(typ.String()) // "int" turns into "Int"
	case *types.Slice:
		switch typ.Elem().String() {
		case "byte":
			return "Bytes"
		case "string":
			return "StringList"
		case "*cuelang.org/go/internal.Decimal":
			return "DecimalList"
		}
		return "List"
	}
	switch typ.String() {
	case "*math/big.Int":
		return "BigInt"
	case "*math/big.Float":
		return "BigFloat"
	case "*cuelang.org/go/internal.Decimal":
		return "Decimal"
	case "cuelang.org/go/internal/pkg.List":
		return "CueList"
	case "cuelang.org/go/internal/pkg.Struct":
		return "Struct"
	case "cuelang.org/go/cue.Value",
		"cuelang.org/go/cue/ast.Expr":
		return "Value"
	case "cuelang.org/go/internal/pkg.Schema":
		g.nonConcrete = true
		return "Schema"
	case "io.Reader":
		return "Reader"
	}
	log.Fatal("callCtxtGetter: unhandled Go type ", typ.String())
	return ""
}

// adtKind provides a Go expression string which describes
// a [cuelang.org/go/internal/core/adt.Kind] value for the given type.
func (g *goEmitter) adtKind(typ types.Type) string {
	// TODO: detect list and structs types for return values.
	switch typ := typ.(type) {
	case *types.Slice:
		if typ.Elem() == typeByte {
			return "adt.BytesKind | adt.StringKind"
		}
		return "adt.ListKind"
	case *types.Map:
		return "adt.StructKind"
	case *types.Basic:
		if typ.Info()&types.IsInteger != 0 {
			return "adt.IntKind"
		}
		if typ.Kind() == types.Float64 {
			return "adt.NumberKind"
		}
		return "adt." + strings.Title(typ.String()) + "Kind" // "bool" turns into "adt.BoolKind"
	}
	switch typ.String() {
	case "error":
		return "adt.BottomKind"
	case validatorType:
		return "adt.BoolKind"
	case "io.Reader":
		return "adt.BytesKind | adt.StringKind"
	case "cuelang.org/go/internal/pkg.Struct":
		return "adt.StructKind"
	case "cuelang.org/go/internal/pkg.List":
		return "adt.ListKind"
	case "*math/big.Int":
		return "adt.IntKind"
	case "*cuelang.org/go/internal.Decimal", "*math/big.Float":
		return "adt.NumberKind"
	case "cuelang.org/go/cue.Value", "cuelang.org/go/cue/ast.Expr", "cuelang.org/go/internal/pkg.Schema":
		return "adt.TopKind" // TODO: can be more precise

	// Some builtin functions return custom types, like [cuelang.org/go/pkg/time.Split].
	// TODO: we can simplify this once the CUE API declarations in ./pkg/...
	// use CUE function signatures to validate their parameters and results.
	case "*cuelang.org/go/pkg/time.Parts":
		return "adt.StructKind"
	case "*cuelang.org/go/pkg/net.ParsedCIDR":
		return "adt.StructKind"
	}
	log.Fatal("adtKind: unhandled Go type ", typ.String())
	return ""
}

// A cueEmitter generates a package's pkg.cue file, which describes
// the package's API for tooling.
type cueEmitter struct {
	filename   string
	cuePkgPath string
	def        *bytes.Buffer
	docs       map[token.Pos]string
	// written records the name of each pkg.cue file written, shared
	// with pruneGeneratedCUE so that stale files can be removed.
	written map[string]bool
}

func newCUEEmitter(dir, cuePkgPath string, pkg *packages.Package, docTxt string, written map[string]bool) *cueEmitter {
	e := &cueEmitter{
		filename:   filepath.Join(dir, "pkg.cue"),
		cuePkgPath: cuePkgPath,
		def:        &bytes.Buffer{},
		docs:       objectDocs(pkg),
		written:    written,
	}
	e.defHeader(pkg, docTxt)
	return e
}

// defHeader emits the header of the CUE definition file: the generated
// code marker, the package documentation, and the package clause.
// docTxt, when non-empty, is the contents of the package's doc.txt
// file, which already holds comment lines.
func (e *cueEmitter) defHeader(pkg *packages.Package, docTxt string) {
	fmt.Fprintf(e.def, "// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.\n\n")
	if docTxt != "" {
		fmt.Fprintf(e.def, "%s\n", strings.TrimRight(docTxt, "\n"))
	} else if doc := packageDoc(pkg); doc != "" {
		writeDefComment(e.def, doc)
	}
	fmt.Fprintf(e.def, "package %s\n\n", path.Base(e.cuePkgPath))
}

func (e *cueEmitter) constant(obj *types.Const, value string) {
	e.defEntry(obj.Pos(), obj.Name(), value)
}

// function emits a function's declaration: a required field — the
// definition file cannot carry the function's value — whose @stdlib
// attribute records the signature.
//
// A builtin intended for use as a validator of its first parameter —
// declared in Go with a Validator result, or with an error result,
// which yields no value at all — is declared in validator form: the
// trailing parameters become the function's parameters and the first
// parameter's type the validator's argument.
func (e *cueEmitter) function(fn *types.Func) {
	sign := fn.Signature()
	params := sign.Params()
	defParams := make([]string, params.Len())
	for i := range defParams {
		defParams[i] = e.defParam(fn.Name(), params.At(i))
	}
	result := e.cueType(sign.Results().At(0).Type())

	var sig string
	validator := sign.Results().At(0).Type().String() == validatorType || result == "_|_"
	switch {
	case validator && params.Len() == 1:
		sig = fmt.Sprintf("validator(%s)", e.cueType(params.At(0).Type()))
	case validator && params.Len() > 1:
		sig = fmt.Sprintf("func(%s) -> validator(%s)",
			strings.Join(defParams[1:], ", "), e.cueType(params.At(0).Type()))
	default:
		sig = fmt.Sprintf("func(%s) -> %s", strings.Join(defParams, ", "), result)
	}
	e.defEntry(fn.Pos(), fn.Name()+"!", fmt.Sprintf("_ @stdlib(%s)", sig))
}

// defEntry emits one member declaration, preceded by the doc comment
// of the Go object declared at pos, if any.
func (e *cueEmitter) defEntry(pos token.Pos, name, value string) {
	if doc := e.docs[pos]; doc != "" {
		writeDefComment(e.def, doc)
	}
	fmt.Fprintf(e.def, "%s: %s\n\n", name, value)
}

// supplementalCUE carries the supplemental declarations over verbatim,
// including their comments; only the license header and package clause
// are dropped.
func (e *cueEmitter) supplementalCUE(_ ast.Expr, src []byte) error {
	e.def.Write(bytes.TrimSpace(src))
	e.def.WriteString("\n")
	return nil
}

// close formats the accumulated CUE definitions and writes them to
// pkg.cue in the package's directory.
func (e *cueEmitter) close() error {
	b, err := cueformat.Source(e.def.Bytes())
	if err != nil {
		return fmt.Errorf("cannot format CUE definitions for %s: %v\n%s", e.cuePkgPath, err, e.def.Bytes())
	}
	if err := os.WriteFile(e.filename, b, 0o666); err != nil {
		return err
	}
	e.written[e.filename] = true
	return nil
}

// pathOSRequired lists the pkg/path builtins whose trailing OS
// parameter is required rather than optional with the "unix" default.
// It mirrors the hand-written pkg/path/pkg.go; drift between the two
// is caught by this directory's tests, which compare every sig
// attribute against the registered builtin's parameters.
var pathOSRequired = map[string]bool{
	"SplitList": true,
	"ToSlash":   true,
	"FromSlash": true,
}

// paramHasDefault reports whether a parameter carries a default when
// its function is called with fewer arguments.
func paramHasDefault(funcName string, param *types.Var) bool {
	return param.Type().String() == "cuelang.org/go/pkg/path.OS" &&
		!pathOSRequired[funcName]
}

// defParam returns the declaration of a function parameter for use in
// a signature. Parameter names carry no calling contract — builtins
// take their arguments by position only — so they are rendered as
// aliases on anonymous positional parameters (_~name: type). An
// unnamed Go parameter is rendered as its bare type.
func (e *cueEmitter) defParam(funcName string, param *types.Var) string {
	name := param.Name()
	typ := e.cueType(param.Type())
	if param.Type().String() == "cuelang.org/go/pkg/path.OS" {
		name = "os"
		if paramHasDefault(funcName, param) {
			typ += ` | *"unix"`
		}
	}
	if name == "" {
		return typ
	}
	return fmt.Sprintf("_~%s: %s", name, typ)
}

// cueType provides CUE syntax describing the values accepted or
// produced for the given Go type, for use in the sig attribute of a
// CUE definition file.
func (e *cueEmitter) cueType(typ types.Type) string {
	switch typ := typ.(type) {
	case *types.Slice:
		if typ.Elem() == typeByte {
			return "bytes|string"
		}
		switch typ.Elem().String() {
		case "string":
			return "[...string]"
		case "*cuelang.org/go/internal.Decimal":
			return "[...number]"
		}
		return "[...]"
	case *types.Map:
		return "{...}"
	case *types.Basic:
		if typ.Info()&types.IsInteger != 0 {
			return "int"
		}
		if typ.Kind() == types.Float64 {
			return "number"
		}
		return typ.String() // "bool" and "string" are CUE types too
	}
	switch typ.String() {
	case "error":
		return "_|_"
	case validatorType:
		return "bool"
	case "io.Reader":
		return "bytes|string"
	case "cuelang.org/go/internal/pkg.Struct":
		return "{...}"
	case "cuelang.org/go/internal/pkg.List":
		return "[...]"
	case "*math/big.Int":
		return "int"
	case "*cuelang.org/go/internal.Decimal", "*math/big.Float":
		return "number"
	case "cuelang.org/go/cue.Value",
		"cuelang.org/go/cue/ast.Expr",
		"cuelang.org/go/internal/pkg.Schema":
		return "_"
	case "cuelang.org/go/pkg/path.OS":
		return "string"

	// Some builtin functions return custom types, like [cuelang.org/go/pkg/time.Split].
	case "*cuelang.org/go/pkg/time.Parts":
		return "{...}"
	case "*cuelang.org/go/pkg/net.ParsedCIDR":
		return "{...}"
	}
	log.Fatal("cueType: unhandled Go type ", typ.String())
	return ""
}

// writeDefComment writes text as a CUE comment group. The text is
// carried over verbatim, preserving indented blocks in Go doc
// comments, unlike [internal.NewComment] which rewraps long lines.
func writeDefComment(w *bytes.Buffer, text string) {
	for _, line := range strings.Split(strings.TrimSuffix(text, "\n"), "\n") {
		if line == "" {
			fmt.Fprintf(w, "//\n")
		} else {
			fmt.Fprintf(w, "// %s\n", line)
		}
	}
}

// objectDocs collects the doc comments of a Go package's declarations,
// keyed by the source position of each declared name. Generated files
// are excluded so that docs come from the hand-written sources only.
// For constants declared in a group, a declaration's trailing line
// comment serves as its doc when it has no doc comment of its own.
func objectDocs(pkg *packages.Package) map[token.Pos]string {
	docs := make(map[token.Pos]string)
	for _, f := range pkg.Syntax {
		if goast.IsGenerated(f) {
			continue
		}
		for _, decl := range f.Decls {
			switch decl := decl.(type) {
			case *goast.FuncDecl:
				if decl.Doc != nil {
					docs[decl.Name.Pos()] = decl.Doc.Text()
				}
			case *goast.GenDecl:
				for _, spec := range decl.Specs {
					spec, ok := spec.(*goast.ValueSpec)
					if !ok {
						continue
					}
					doc := spec.Doc.Text()
					if doc == "" && len(decl.Specs) == 1 {
						doc = decl.Doc.Text()
					}
					if doc == "" {
						doc = spec.Comment.Text()
					}
					if doc == "" {
						continue
					}
					for _, name := range spec.Names {
						docs[name.Pos()] = doc
					}
				}
			}
		}
	}
	return docs
}

// packageDoc returns the Go package documentation: the doc comment of
// the first hand-written file that has one.
func packageDoc(pkg *packages.Package) string {
	for _, f := range pkg.Syntax {
		if f.Doc != nil && !goast.IsGenerated(f) {
			return f.Doc.Text()
		}
	}
	return ""
}
