// Code generated by cuelang.org/go/pkg/gen. DO NOT EDIT.

package md5

// The size of an MD5 checksum in bytes.
Size: 16

// The blocksize of MD5 in bytes.
BlockSize: 64

// Sum returns the MD5 checksum of the data.
Sum!: _ @stdlib(func(_~data: bytes|string) -> bytes|string)
